import fs from 'node:fs';import YAML from 'yaml';
const out=new URL('../entrega_examen/contratos/',import.meta.url);
const props={amount:{oneOf:[{type:'string',pattern:'^\\d+(\\.\\d{1,2})?$'},{type:'number',exclusiveMinimum:0}],description:'Monto MXN; hasta dos decimales'},account_number:{type:'string',pattern:'^\\d{12}$'},pin:{type:'string',pattern:'^\\d{4}$',writeOnly:true},email:{type:'string',format:'email'},password:{type:'string',writeOnly:true},holder_name:{type:'string',maxLength:120},initial_balance:{type:['string','number']},type:{type:'string',enum:['branch','atm']},name:{type:'string',maxLength:100},responsible:{type:'string',maxLength:100},initial_cash:{type:['string','number']},status:{type:'string',enum:['active','blocked']},central_url:{type:'string',format:'uri'},api_key:{type:'string',writeOnly:true},source_account:{type:'string',pattern:'^\\d{12}$'},destination_account:{type:'string',pattern:'^\\d{12}$'}};
const header=(name,required=true)=>({name,in:'header',required,schema:{type:'string'}});
function spec(title,port,cookie){return{openapi:'3.1.0',info:{title,version:'1.0.0',description:'Sistema Bancario Distribuido. JSON, MXN; las operaciones monetarias utilizan idempotencia.'},servers:[{url:`http://localhost:${port}/api/v1`,description:'Entorno del nodo'}],paths:{},components:{securitySchemes:{Session:{type:'apiKey',in:'cookie',name:cookie},NodeKey:{type:'apiKey',in:'header',name:'X-API-Key'},AccountPin:{type:'apiKey',in:'header',name:'X-Account-Pin'},AdminToken:{type:'http',scheme:'bearer'}},schemas:{Success:{type:'object',required:['data'],properties:{data:{description:'Resultado de la operación'}}},Error:{type:'object',required:['error'],properties:{error:{type:'object',required:['code','message'],properties:{code:{type:'string'},message:{type:'string'}}}}}}}};}
function add(s,path,method,summary,{auth='session',body=[],money=false,query=[],csrf=true}={}){const sec=auth==='public'?[]:auth==='node'?[{NodeKey:[]}]:auth==='pin'?[{NodeKey:[],AccountPin:[]}]:[{Session:[]}];const op={summary,operationId:method+'_'+path.replace(/[^a-zA-Z0-9]/g,'_'),security:sec,parameters:[],responses:{'200':{description:'Consulta o repetición idempotente',content:{'application/json':{schema:{$ref:'#/components/schemas/Success'}}}},default:{description:'Error de validación, autorización, fondos, efectivo o disponibilidad',content:{'application/json':{schema:{$ref:'#/components/schemas/Error'}}}}}};for(const match of path.matchAll(/\{(\w+)\}/g))op.parameters.push({name:match[1],in:'path',required:true,schema:{type:'string'}});for(const name of query)op.parameters.push({name,in:'query',schema:{type:'string'}});if(money)op.parameters.push(header('Idempotency-Key'));if(method!=='get'&&csrf&&(auth==='session'||auth==='public'))op.parameters.push(header('X-CSRF-TOKEN'));if(body.length)op.requestBody={required:true,content:{'application/json':{schema:{type:'object',required:body,properties:Object.fromEntries(body.map(n=>[n,props[n]||{type:'string'}]))}}}};if(method==='post'&&money||path==='/admin/nodes'&&method==='post')op.responses['201']={description:'Operación creada',content:{'application/json':{schema:{$ref:'#/components/schemas/Success'}}}};if(path.endsWith('/reports'))op.responses['200'].content['text/csv']={schema:{type:'string'}};if(!op.parameters.length)delete op.parameters;s.paths[path]??={};s.paths[path][method]=op;}
const core=spec('Banco central — Laravel',8100,'banco_central_session');
for(const [p,summary] of [['/health','Estado del servicio'],['/csrf','Obtener token CSRF']])add(core,p,'get',summary,{auth:'public'});
add(core,'/auth/login','post','Iniciar sesión administrativa',{auth:'public',body:['email','password']});add(core,'/auth/logout','post','Cerrar sesión');
for(const [p,label]of [['/admin/dashboard','Resumen central'],['/admin/nodes','Listar nodos'],['/admin/accounts','Listar cuentas']])add(core,p,'get',label);
add(core,'/admin/nodes','post','Crear nodo y emitir su API key una sola vez',{body:['type','name','responsible','initial_cash']});add(core,'/admin/nodes/{id}','patch','Actualizar nodo y responsable',{body:['responsible']});add(core,'/admin/nodes/{id}/cash','post','Dispersar efectivo',{body:['amount']});add(core,'/admin/nodes/{id}/rotate-key','post','Rotar API key');add(core,'/admin/accounts/{number}/status','patch','Activar/bloquear cuenta',{body:['status']});
for(const p of ['/admin/transactions','/admin/reports'])add(core,p,'get','Historial o reporte global',{query:['node_id','account_number','type','from','to',...(p.endsWith('reports')?['format']:[])]});
add(core,'/node','get','Identidad y efectivo del nodo',{auth:'node'});add(core,'/accounts','get','Cuentas de la sucursal',{auth:'node'});add(core,'/accounts','post','Abrir cuenta desde sucursal',{auth:'node',body:['holder_name','initial_balance','pin'],money:true});add(core,'/accounts/{number}/balance','get','Consultar saldo central',{auth:'pin'});add(core,'/transactions','get','Historial del nodo',{auth:'node',query:['account_number','type','from','to']});
for(const [p,label,body]of [['/withdrawals','Retirar con verificación de saldo y efectivo',['account_number','amount']],['/deposits','Abonar a cuenta',['account_number','amount']],['/transfers','Transferencia atómica',['source_account','destination_account','amount']]])add(core,p,'post',label,{auth:'pin',body,money:true});
const branch=spec('Sucursal — Laravel',8001,'sucursal_session');const atm=spec('Cajero — Express',3000,'atm_session');
for(const s of [branch,atm]){add(s,'/health','get','Salud',{auth:'public'});add(s,'/csrf','get','Token CSRF',{auth:'public'});add(s,'/auth/login','post','Iniciar sesión administrativa',{auth:'public',body:['email','password']});add(s,'/auth/logout','post','Cerrar sesión');add(s,'/config','get','Consultar configuración sin revelar key');add(s,'/config','put','Guardar y verificar API key',{body:['central_url','api_key']});}
add(branch,'/dashboard','get','Resumen de sucursal');add(branch,'/accounts','get','Cuentas de la sucursal');add(branch,'/accounts','post','Registrar cliente en central',{body:['holder_name','initial_balance','pin'],money:true});for(const p of ['/transactions','/reports'])add(branch,p,'get','Historial y reporte local',{query:['account_number','from','to',...(p==='/reports'?['format']:['type'])]});
add(atm,'/node','get','Efectivo y disponibilidad',{auth:'public'});add(atm,'/customer/login','post','Autenticar cliente con cuenta/PIN',{auth:'public',body:['account_number','pin']});add(atm,'/customer/logout','post','Finalizar sesión de cliente');add(atm,'/balance','get','Saldo del cliente autenticado');for(const p of ['/withdrawals','/deposits','/transfers'])add(atm,p,'post','Operación del cliente autenticado',{body:p==='/transfers'?['destination_account','amount']:['amount'],money:true});add(atm,'/transactions','get','Historial del cliente o administrador',{query:['account_number']});
for(const [name,s]of [['banco-central',core],['sucursal',branch],['cajero',atm]]){fs.writeFileSync(new URL(name+'.openapi.yaml',out),YAML.stringify(s));console.log('OpenAPI',name,Object.keys(s.paths).length,'paths');}
