import {chromium} from 'playwright-core';import fs from 'node:fs';
const root=new URL('../',import.meta.url);const access=JSON.parse(fs.readFileSync(new URL('.runtime/access.json',root)));const browser=await chromium.launch({executablePath:'/opt/brave.com/brave/brave',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
const shots=new URL('docs/capturas/',root);const evidence={timestamp:new Date().toISOString(),checks:[]};
async function shot(page,name){await page.screenshot({path:new URL(name+'.png',shots).pathname,fullPage:true});console.log('Captured',name);}
async function login(url,creds){const ctx=await browser.newContext({viewport:{width:1440,height:1050},locale:'es-MX'});const page=await ctx.newPage();page.on('pageerror',e=>console.log('Browser error',e.message));await page.goto(url);await page.locator('input[name=email]').waitFor();await page.fill('input[name=email]',creds.email);await page.fill('input[name=password]',creds.password);await page.locator('#login-form button').click();await page.getByRole('button',{name:'Cerrar sesión'}).waitFor();return page;}
try{
 const central=await login('http://127.0.0.1:8100',access.central);await central.getByRole('button',{name:'Sucursales y cajeros',exact:true}).click();await central.getByRole('heading',{name:'Nodos registrados'}).waitFor();await shot(central,'01-nodos-central');
 const branch=await login('http://127.0.0.1:8001',access.branch);await branch.getByRole('button',{name:'Apertura de cuentas',exact:true}).click();await branch.locator('#account-form').waitFor();await shot(branch,'02-apertura-sucursal');await branch.fill('input[name=holder_name]','Cliente Demostración');await branch.fill('input[name=initial_balance]','1000');await branch.fill('input[name=pin]','1234');await branch.locator('#account-form button').click();await branch.locator('#created-account').waitFor({timeout:45000});const account=(await branch.locator('#created-account').textContent()).trim();evidence.account_number=account;await shot(branch,'03-cuenta-creada');evidence.checks.push({name:'Apertura desde sucursal',passed:true,balance:'1000.00'});
 await central.getByRole('button',{name:'Cuentas',exact:true}).click();await central.locator('td').filter({hasText:account}).waitFor();await shot(central,'04-cuenta-central-inicial');
 const atmctx=await browser.newContext({viewport:{width:1440,height:1100},locale:'es-MX'});const atm=await atmctx.newPage();let withdrawalKey;atm.on('request',r=>{if(r.url().endsWith('/api/v1/withdrawals')&&r.method()==='POST')withdrawalKey=r.headers()['idempotency-key'];});await atm.goto('http://127.0.0.1:3000');await atm.locator('input[name=account_number]').waitFor();await atm.fill('input[name=account_number]',account);await atm.fill('input[name=pin]','1234');await atm.locator('#login-form button').click();await atm.getByRole('button',{name:'↓ Retirar efectivo'}).waitFor({timeout:45000});await shot(atm,'05-saldo-atm-inicial');await atm.getByRole('button',{name:'↓ Retirar efectivo'}).click();await atm.fill('input[name=amount]','300');await shot(atm,'06-retiro-atm');await atm.locator('#operation-form button').click();await atm.getByRole('heading',{name:'✓ Operación realizada'}).waitFor({timeout:45000});await shot(atm,'07-comprobante-retiro');evidence.withdrawal_key=withdrawalKey;evidence.checks.push({name:'Retiro desde ATM remoto',passed:true,amount:'300.00',balance:'700.00'});
 await central.getByRole('button',{name:'Resumen',exact:true}).click();await central.getByRole('button',{name:'Cuentas',exact:true}).click();await central.locator('td').filter({hasText:account}).waitFor();await shot(central,'08-saldo-central-final');
 await central.getByRole('button',{name:'Historial y reportes',exact:true}).click();await central.locator('#tx-table').waitFor();await shot(central,'09-historial-central');
 await atm.getByRole('button',{name:'↓ Retirar efectivo'}).click();await atm.fill('input[name=amount]','900');await atm.locator('#operation-form button').click();await atm.locator('.notice.error').waitFor({timeout:45000});await shot(atm,'10-rechazo-saldo-insuficiente');evidence.checks.push({name:'Rechazo por saldo insuficiente',passed:true});
 await central.getByRole('button',{name:'Sucursales y cajeros',exact:true}).click();await central.getByRole('heading',{name:'Nodos registrados'}).waitFor();await shot(central,'11-efectivo-atm-final');
 fs.writeFileSync(new URL('.runtime/evidence.json',root),JSON.stringify(evidence,null,2),{mode:0o600});console.log(JSON.stringify({account_number:account,checks:evidence.checks}));
}finally{await browser.close();}
