import pg from 'pg';import fs from 'node:fs';import {randomUUID} from 'node:crypto';
const root=new URL('../',import.meta.url),c=JSON.parse(fs.readFileSync(new URL('.runtime/connections.json',root))).central_db,n=JSON.parse(fs.readFileSync(new URL('.runtime/nodes.json',root)));const db=new pg.Client({...c,database:'postgres',ssl:{rejectUnauthorized:false}});await db.connect();const account=(await db.query("select account_number,balance_cents from users_accounts where holder_name='Cliente Demostración' order by created_at desc limit 1")).rows[0];const tx=(await db.query("select id,idempotency_key,amount_cents,node_id from transactions where source_account=$1 and type='withdrawal' order by created_at limit 1",[account.account_number])).rows[0];const result={timestamp:new Date().toISOString(),account_number:account.account_number,checks:[]};
async function call(route,{method='GET',body,key=n.atm.api_key,pin='1234',idem}={}){const r=await fetch('http://127.0.0.1:8100/api/v1/'+route,{method,headers:{Accept:'application/json','Content-Type':'application/json','X-API-Key':key,'X-Account-Pin':pin,...(idem?{'Idempotency-Key':idem}:{})},...(body?{body:JSON.stringify(body)}:{})});return{status:r.status,body:await r.json()};}
function check(name,ok,details){result.checks.push({name,passed:!!ok,...details});if(!ok)throw new Error(name);console.log('PASS',name);}
try{
 check('Saldo final central',Number(account.balance_cents)===70000,{balance:'700.00'});
 const replay=await call('withdrawals',{method:'POST',body:{account_number:account.account_number,amount:'300'},idem:tx.idempotency_key});check('Repetición idempotente sin segundo retiro',replay.status===200&&replay.body.data?.replayed&&replay.body.data.balance==='700.00',{status:replay.status,transaction_id:tx.id});
 const conflict=await call('withdrawals',{method:'POST',body:{account_number:account.account_number,amount:'301'},idem:tx.idempotency_key});check('Conflicto de idempotencia',conflict.status===409,{status:conflict.status});
 const funds=await call('withdrawals',{method:'POST',body:{account_number:account.account_number,amount:'900'},idem:randomUUID()});check('Saldo insuficiente',funds.status===409&&funds.body.error?.code==='INSUFFICIENT_FUNDS',{status:funds.status});
 const badkey=await call('node',{key:'invalid-key'});check('API key inválida',badkey.status===401,{status:badkey.status});
 const badpin=await call('accounts/'+account.account_number+'/balance',{pin:'9999'});check('PIN inválido',badpin.status===401,{status:badpin.status});
 for(const [name,sql]of [['Historial rechazó UPDATE','update transactions set amount_cents=amount_cents where id=$1'],['Historial rechazó DELETE','delete from transactions where id=$1']]){await db.query('begin');let rejected=false;try{await db.query(sql,[tx.id]);}catch(e){rejected=e.message.includes('immutable');}finally{await db.query('rollback');}check(name,rejected,{});}
 const final=(await db.query('select balance_cents from users_accounts where account_number=$1',[account.account_number])).rows[0];check('Saldo permaneció en $700 después de las pruebas',Number(final.balance_cents)===70000,{});
 const local=JSON.parse(fs.readFileSync(new URL('.runtime/connections.json',root))).nodes_db;const l=new pg.Client({...local,database:'postgres',ssl:{rejectUnauthorized:false}});await l.connect();const count=(await l.query('select count(*) from node_events where central_transaction_id=$1',[tx.id])).rows[0].count;check('Retiro persistido en Supabase ATM/Sucursal',Number(count)===1,{});await l.end();
 fs.writeFileSync(new URL('entrega_examen/resultado_pruebas.json',root),JSON.stringify(result,null,2));console.log('Validación bancaria completa.');
}finally{await db.end();}
